from werkzeug.security import generate_password_hash
from portfolio import create_app,db
from portfolio.models import Project,AdminUser
app=create_app()
items=[
 dict(slug='sword-masters',title='Sword Masters',short_description='A Roblox sword progression game with worlds, upgrades and polished UI.',full_description='Sword Masters is a Roblox game focused on satisfying progression, collectible weapons and replayable combat.',category='Roblox',status='In Development',featured=True,technologies='Roblox Studio,Lua,UI Design',features='Sword progression,World unlocks,Upgrades,Responsive UI',goals='Polished progression,Strong branding,Mobile support',development_process='Built with reusable modules and frequent gameplay testing.',progress=72,cover_image='https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80'),
 dict(slug='zine',title='Zine',short_description='A clean short-form video social platform inspired by Vine.',full_description='Zine is designed around quick clips, creator profiles and simple discovery.',category='Websites',status='Live',featured=True,technologies='Web Design,JavaScript,Vercel',features='Video feed,Profiles,Responsive layout',goals='Fast discovery,Simple navigation,Strong identity',development_process='Designed mobile-first and deployed on modern hosting.',progress=90,live_url='https://zine.video',cover_image='https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&w=1200&q=80'),
 dict(slug='solarcord',title='SolarCord',short_description='A Discord-inspired community platform concept.',full_description='SolarCord explores servers, channels, profiles and community tools in a modern interface.',category='Websites',status='Concept',featured=True,technologies='Python,Flask,UI Design',features='Servers,Channels,Profiles,Roles',goals='Clean communication,Unique branding,Community tools',development_process='Started with UI planning and full-stack architecture.',progress=48,cover_image='https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=80'),
 dict(slug='discord-template-bot',title='Discord Template Bot',short_description='A Python bot that creates channels, roles, permissions and embeds.',full_description='This bot quickly creates professional Discord server structures in multiple sizes.',category='Bots',status='In Development',featured=True,technologies='Python,Discord.py,Automation',features='Template generation,Roles,Permissions,Rules embeds',goals='Faster setup,Professional defaults,Flexible themes',development_process='Uses reusable command-driven templates.',progress=68,cover_image='https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&w=1200&q=80'),
 dict(slug='evolutions-smp',title='Evolutions SMP',short_description='A Minecraft lifesteal, economy and PvP survival server.',full_description='A custom Minecraft community with ranks, scoreboards, tab lists and progression.',category='Minecraft',status='Active',featured=False,technologies='Paper,Plugins,Server Design',features='Lifesteal,Economy,PvP,Ranks',goals='Strong community,Polished branding,Fun progression',development_process='Configured with Paper and carefully selected plugins.',progress=82,cover_image='https://images.unsplash.com/photo-1603481546238-487240415921?auto=format&fit=crop&w=1200&q=80'),
 dict(slug='roblox-ui-pack',title='Roblox UI Pack',short_description='Reusable buttons, panels, icons and interfaces.',full_description='A reusable design pack for clean and scalable Roblox interfaces.',category='Design',status='Ongoing',featured=False,technologies='Roblox Studio,Photoshop,UI Design',features='Buttons,Panels,Icons,Mobile layouts',goals='Consistent assets,Faster workflow,Multiple themes',development_process='Components are tested at several screen sizes.',progress=60,cover_image='https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=80')
]
with app.app_context():
 db.drop_all();db.create_all();db.session.add(AdminUser(username='admin',password_hash=generate_password_hash('change-me-now')));[db.session.add(Project(**x)) for x in items];db.session.commit();print('Ready. Login: admin / change-me-now')
